language: android

android:
  components:
    - build-tools-20.0.0
    - android-20
    - sys-img-armeabi-v7a-android-wear-20

before_script:
  - echo no | android create avd --force -n test -t android-20 -g android-wear --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
